spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8nnvekvikkc73d3lfdg-a.oregon-postgres.render.com:5432/mth_cng5}
#spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.username=${DB_USERNAME:postgres_user}
spring.datasource.password=${DB_PASSWORD:4ZbuyM7DiT7wRfnLiwmzD0WXE4ca3F3b}

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001